configure: Don't require pcsclite header for winscard.
The header is unused, and the header check fails with:

configure:7860: checking for PCSC/pcsclite.h
configure:7860: gcc -m32 -c -g -O2  conftest.c >&5
In file included from conftest.c:50:
[...]/include/PCSC/pcsclite.h:45:10:
fatal error: wintypes.h: No such file or directory
   45 | #include <wintypes.h>
         |          ^~~~~~~~~~~~

Fixes: d405a688ba6b5042775d733f57d00ba6318e1d0f