ntdll: Do not check for malloc() failure in get_initial_environment.
This is called early in process startup; malloc() should definitely never fail here.

This fixes an uninitialized variable warning with gcc 12.2:

In function ‘build_initial_params’,
    inlined from ‘init_startup_info’ at ../wine/dlls/ntdll/unix/env.c:2004:18:
../wine/dlls/ntdll/unix/env.c:1910:12: error: ‘env_pos’ may be used uninitialized [-Werror=maybe-uninitialized]
 1910 |     path = get_env_var( env, env_pos, pathW, 4 );
      |            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../wine/dlls/ntdll/unix/env.c: In function ‘init_startup_info’:
../wine/dlls/ntdll/unix/env.c:1903:18: note: ‘env_pos’ declared here
 1903 |     SIZE_T size, env_pos, env_size;
      |                  ^~~~~~~