nsiproxy: Include sys/queue.h from tcp.c.
In what looks like a change between FreeBSD 11 and later versions
(FreeBSD 12 and 13), we now need to explicitly include sys/queue.h
to avoid

  In file included from dlls/nsiproxy.sys/tcp.c:42:
  /usr/include/netinet/tcp_var.h:516:2: error:
  expected specifier-qualifier-list before 'TAILQ_ENTRY'
  516 | TAILQ_ENTRY(tcptw)  tw_2msl;

Signed-off-by: Gerald Pfeifer <gerald@pfeifer.com>
Signed-off-by: Huw Davies <huw@codeweavers.com>
Signed-off-by: Alexandre Julliard <julliard@winehq.org>