include: Add Windows.Media.Effects.AudioEffect runtimeclass.
This is required for chromium and fixes the following compiler error.

In file included from media/audio/win/audio_low_latency_input_win.cc:5:
./media/audio/win/audio_low_latency_input_win.h:64:10: fatal error:
windows.media.effects.h: No such file or directory
   64 | #include <windows.media.effects.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~