include: Fix c++ compiler error with msxml2.idl.
This moves ISAXXMLFilter declaration after its base class ISAXXMLReader.
Otherwise the following error is shown in C++ mode

$ wineg++ test-msxml2.cpp
In file included from test-msxml2.cpp:1:
/usr/include/wine/windows/msxml2.h:16199:24: error: invalid use of incomplete type ‘struct ISAXXMLReader’
16199 | ISAXXMLFilter : public ISAXXMLReader
|                        ^~~~~~~~~~~~~
/usr/include/wine/windows/msxml2.h:644:19: note: forward declaration of ‘struct ISAXXMLReader’
644 | typedef interface ISAXXMLReader ISAXXMLReader;
|                   ^~~~~~~~~~~~~
winegcc: /usr/bin/g++ failed

Signed-off-by: Biswapriyo Nath <nathbappai@gmail.com>
(cherry picked from commit 787c3f73f8a3d4dc9dd653245f4967998d239be1)