propsys/tests: Fix build with MSVC.
VC2010 does not allow initializing a struct inside a struct with a variable.

E.g.
error C2440: 'initializing' : cannot convert from 'PROPERTYKEY' to 'unsigned long'

Signed-off-by: Thomas Faber <thomas.faber@reactos.org>
Signed-off-by: Alexandre Julliard <julliard@winehq.org>