libwine: Avoid comparing the result of pointer arithmetic to zero.
gcc warns about this:

../wine/libs/wine/mmap.c: In function ‘wine_mmap_add_reserved_area_obsolete’:
../wine/libs/wine/mmap.c:504:9: error: the comparison will always evaluate as ‘true’ for the pointer operand in ‘(char *)addr + (sizetype)size’ must not be NULL [-Werror=address]
  504 |     if (!((char *)addr + size)) size--;  /* avoid wrap-around */
      |         ^

(cherry picked from commit d17fe0a7920c09a16e75b74213ae0e8bbbd1cba0)
Signed-off-by: Michael Stefaniuc <mstefani@winehq.org>